// <auto-generated />
using System;
using Bridge.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bridge.Storage.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    [Migration("20260822215454_AddMetadataSyncMarkers")]
    partial class AddMetadataSyncMarkers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bridge.Core.Entities.AgeRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgeRatings");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Bridge.Core.Entities.CompletionStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CompletionStatuses");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Emulator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Emulators");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRatingIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommunityScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompletionStatusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CriticScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionBlocks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionImages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeveloperIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStartedScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("InstallSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LinksSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeToBeatSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverrideInstallState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlaytimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Roms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Screenshots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("TimeToBeatCompleteSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TimeToBeatExtraSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TimeToBeatMainSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGlobalGameStartedScript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGlobalPostScript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGlobalPreScript")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "SourceId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Bridge.Core.Entities.GameFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameFeatures");
                });

            modelBuilder.Entity("Bridge.Core.Entities.GameScannerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrcExcludeFileTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmulatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExcludeOnlineFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludedDirectories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImportWithRelativePaths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MergeRelatedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OverridePlatformId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayActionMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScanInsideArchives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScanSubfolders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSimplifiedOnlineFileScan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameScanners");
                });

            modelBuilder.Entity("Bridge.Core.Entities.GameSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameSources");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Bridge.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
